
package com.jk.ws.user.imp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.jk.ws.user.ObjectFactory;
import com.jk.ws.user.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSUserService", targetNamespace = "http://user.ws.jk.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSUserService {


    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserById", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.UpdateUserById")
    @ResponseWrapper(localName = "updateUserByIdResponse", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.UpdateUserByIdResponse")
    public void updateUserById(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUserById", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.DeleteUserById")
    @ResponseWrapper(localName = "deleteUserByIdResponse", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.DeleteUserByIdResponse")
    public void deleteUserById(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.AddUserResponse")
    public void addUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @return
     *     returns java.util.List<com.jk.ws.user.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectUserList", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.SelectUserList")
    @ResponseWrapper(localName = "selectUserListResponse", targetNamespace = "http://user.ws.jk.com/", className = "com.jk.ws.user.SelectUserListResponse")
    public List<User> selectUserList();

}
