
package com.jk.ws.user.imp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSUserServiceImpService", targetNamespace = "http://imp.user.ws.jk.com/", wsdlLocation = "http://localhost:8080/webservice/WSUserServiceImp?wsdl")
public class WSUserServiceImpService
    extends Service
{

    private final static URL WSUSERSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSUSERSERVICEIMPSERVICE_EXCEPTION;
    private final static QName WSUSERSERVICEIMPSERVICE_QNAME = new QName("http://imp.user.ws.jk.com/", "WSUserServiceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/webservice/WSUserServiceImp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSUSERSERVICEIMPSERVICE_WSDL_LOCATION = url;
        WSUSERSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public WSUserServiceImpService() {
        super(__getWsdlLocation(), WSUSERSERVICEIMPSERVICE_QNAME);
    }

    public WSUserServiceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSUSERSERVICEIMPSERVICE_QNAME, features);
    }

    public WSUserServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, WSUSERSERVICEIMPSERVICE_QNAME);
    }

    public WSUserServiceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSUSERSERVICEIMPSERVICE_QNAME, features);
    }

    public WSUserServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSUserServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSUserService
     */
    @WebEndpoint(name = "WSUserServiceImpPort")
    public WSUserService getWSUserServiceImpPort() {
        return super.getPort(new QName("http://imp.user.ws.jk.com/", "WSUserServiceImpPort"), WSUserService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSUserService
     */
    @WebEndpoint(name = "WSUserServiceImpPort")
    public WSUserService getWSUserServiceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://imp.user.ws.jk.com/", "WSUserServiceImpPort"), WSUserService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSUSERSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw WSUSERSERVICEIMPSERVICE_EXCEPTION;
        }
        return WSUSERSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
